// export interface Address {
//   label: string;
//   street: string;
//   city: string;
//   state: string;
//   postalCode: string;
//   country: string;
//   isDefault: boolean;
// }

// export interface User {
//   _id?: string; // optional because it's generated by backend
//   name: string;
//   email: string;
//   password?: string; // optional for cases where password isn't returned
//   passwordHash?: string; // optional for backend responses
//   role: 'customer' | 'admin';
//   phone?: string;
//   addresses?: Address[];
//   createdAt?: Date;
//   updatedAt?: Date;
// }
export interface Address {
  label: string;
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  isDefault: boolean;
}

export interface User {
  _id?: string;
  name: string;
  email: string;
  password?: string;
  role: 'customer' | 'admin';
  phone?: string;
  addresses?: Address[];
  createdAt?: Date;
  updatedAt?: Date;
}